[package]
name = "flatten_filenames"
version = "0.1.0"
authors = ["Brett Cannon <brett@python.org>"]

[[bin]]
name = "flatten-filenames"
path = "src/main.rs"

[dependencies]

[dev-dependencies]
tempdir = "0.3.5"
